# Generated by Django 6.1.1 on 2026-09-05 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='studentprofile',
            new_name='students_st_grade_6d415c_idx',
            old_name='students_stu_grade_c4f7d5_idx',
        ),
        migrations.RenameIndex(
            model_name='studentprofile',
            new_name='students_st_points_35853d_idx',
            old_name='students_stu_points_7c3b8f_idx',
        ),
    ]
