# Generated by Django 6.1.1 on 2026-09-06 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_rename_students_stu_grade_c4f7d5_idx_students_st_grade_6d415c_idx_and_more'),
        ('students', '0002_studentprofile_xp'),
    ]

    operations = [
    ]
