# Generated by Django 6.1.1 on 2026-09-06 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_merge_20260906_1113'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='studentprofile',
            new_name='students_st_xp_2caca1_idx',
            old_name='students_stu_xp_8d4f7b_idx',
        ),
    ]
