# Generated by Django 6.1.1 on 2026-09-05 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_core_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='classroom',
            new_name='core_classr_grade_e39fb1_idx',
            old_name='core_classr_grade_i_2a4d25_idx',
        ),
        migrations.RenameIndex(
            model_name='classroom',
            new_name='core_classr_teacher_2c0b8a_idx',
            old_name='core_classr_teacher_6c3b3b_idx',
        ),
    ]
