# Generated by Django 6.1.1 on 2026-09-05 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0002_rename_students_stu_grade_c4f7d5_idx_students_st_grade_6d415c_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='آزمون تعیین سطح پایه ششم', max_length=160)),
                ('grade', models.PositiveSmallIntegerField(default=6)),
                ('duration_minutes', models.PositiveSmallIntegerField(default=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PlacementQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('option_a', models.CharField(max_length=300)),
                ('option_b', models.CharField(max_length=300)),
                ('option_c', models.CharField(max_length=300)),
                ('option_d', models.CharField(max_length=300)),
                ('correct_option', models.CharField(choices=[('A', 'گزینه ۱'), ('B', 'گزینه ۲'), ('C', 'گزینه ۳'), ('D', 'گزینه ۴')], max_length=1)),
                ('subject', models.CharField(choices=[('math', 'ریاضی'), ('science', 'علوم'), ('persian', 'فارسی'), ('social', 'مطالعات اجتماعی')], default='math', max_length=20)),
                ('difficulty', models.PositiveSmallIntegerField(default=2)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.placementtest')),
            ],
            options={
                'ordering': ['order', 'id'],
                'indexes': [models.Index(fields=['test', 'is_active', 'order'], name='exams_place_test_id_8f31dc_idx'), models.Index(fields=['subject', 'difficulty'], name='exams_place_subject_2d7ce7_idx')],
            },
        ),
        migrations.CreateModel(
            name='PlacementAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('correct_answers', models.PositiveSmallIntegerField(default=0)),
                ('total_questions', models.PositiveSmallIntegerField(default=0)),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_attempts', to='students.studentprofile')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='exams.placementtest')),
            ],
            options={
                'ordering': ['-completed_at', '-id'],
                'indexes': [models.Index(fields=['student', '-completed_at'], name='exams_place_student_9188d0_idx')],
            },
        ),
    ]
