# Generated by Django 6.1.1 on 2026-09-11 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_placement_repeat_approval'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='placementattempt',
            new_name='exams_place_answer__14142a_idx',
            old_name='exams_place_answer__b2b8b1_idx',
        ),
        migrations.RenameIndex(
            model_name='placementattempt',
            new_name='exams_place_student_102eed_idx',
            old_name='exams_place_student_2b8c4e_idx',
        ),
        migrations.RenameIndex(
            model_name='placementdiagnosticresult',
            new_name='exams_place_attempt_98eff1_idx',
            old_name='exams_place_attempt__idx',
        ),
        migrations.RenameIndex(
            model_name='placementdiagnosticresult',
            new_name='exams_place_subject_8d0dd3_idx',
            old_name='exams_place_subject__idx',
        ),
        migrations.RenameIndex(
            model_name='placementquestion',
            new_name='exams_place_subject_fd50f3_idx',
            old_name='exams_plac_subject_9e6c7a_idx',
        ),
    ]
