# Generated by Django 6.1.1 on 2026-09-06 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='practiceattempt',
            new_name='practice_pr_student_57b392_idx',
            old_name='practice_pr_student_3e54a4_idx',
        ),
        migrations.RenameIndex(
            model_name='practiceattempt',
            new_name='practice_pr_questio_c9ab69_idx',
            old_name='practice_pr_question_1a4f2b_idx',
        ),
        migrations.RenameIndex(
            model_name='practicequestion',
            new_name='practice_pr_level_924fc6_idx',
            old_name='practice_pr_level_a1b6a6_idx',
        ),
        migrations.RenameIndex(
            model_name='practicequestion',
            new_name='practice_pr_is_acti_75ccfc_idx',
            old_name='practice_pr_is_acti_4b8c7b_idx',
        ),
    ]
