# Generated by Django 6.1.1 on 2026-09-11 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0003_seed_grade6_practice'),
        ('students', '0004_rename_students_stu_xp_8d4f7b_idx_students_st_xp_2caca1_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMissionCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_code', models.CharField(max_length=50)),
                ('mission_date', models.DateField()),
                ('reward_xp', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_mission_completions', to='students.studentprofile')),
            ],
            options={
                'ordering': ['-mission_date', '-created_at', '-id'],
                'indexes': [models.Index(fields=['student', 'mission_date'], name='practice_da_student_5ff076_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'mission_code', 'mission_date'), name='unique_student_daily_mission')],
            },
        ),
    ]
