# Generated by Django 6.1.1 on 2026-09-11 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_purchase_authority'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='purchase',
            new_name='subscriptio_user_id_d1e61a_idx',
            old_name='subscriptio_user_id_8d0b36_idx',
        ),
        migrations.RenameIndex(
            model_name='purchase',
            new_name='subscriptio_product_c673fd_idx',
            old_name='subscriptio_product_7d0e5b_idx',
        ),
        migrations.RenameIndex(
            model_name='subscription',
            new_name='subscriptio_user_id_1da32d_idx',
            old_name='subscriptio_user_id_6a6bb4_idx',
        ),
    ]
